server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/Jinsub/Documents/Playground/Spring-Boot-MSA/git-local-repo