server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinsub-kim-dev/Spring-Boot-MSA
          searchPaths: tree/main/spring-cloud-config
