server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinsub-kim-dev/Spring-Boot-MSA
          searchPaths: spring-cloud-config
          username: jinsub-kim-dev
          password: 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
          default-label: main
