server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinsub-kim-dev/Spring-Boot-MSA
          searchPaths: spring-cloud-config
          username: jinsub-kim-dev
          password: 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
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh